defaultPlatforms:
  - linux/arm64
  - linux/amd64
builds:
- id: overlock
  dir: . 
  main: ./cmd/overlock
  flags:
  - -tags
  - "{{.Env.VERSION}}"
  ldflags:
  - -s -w
  - -extldflags "-static"
  - -X "github.com/web-seven/overlock/cmd/overlock/version.Version={{.Env.VERSION}}"
